---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibanadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibanadep
  template:
    metadata:
      labels:
        app: kibanadep
    spec:
      containers:
      - image: kibana:7.9.2
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
          - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://esdep:80
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      restartPolicy: Always
