apiVersion: v1
kind: Service
metadata:
  name: kibanadep
spec:
  ports:
  - port: 80 #port to export outwards
    protocol: TCP
    targetPort: 5601 #port to target on pod
  selector:
    app: kibanadep
  type: LoadBalancer
  loadBalancerIP: 192.168.0.12
