apiVersion: v1
kind: Service
metadata:
  name: homeass
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeass
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.16