---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafanadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanadep
  template:
    metadata:
      labels:
        app: grafanadep
    spec:
      containers:
      - image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
          - containerPort: 3000
        env:
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://0.0.0.0:%(http_port)s/grafana/"
        resources:
          requests:
            memory: "250Mi"
            cpu: "0.25"
          limits:
            memory: "500Mi"
            cpu: "0.5"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: pvc-storage
      volumes:
        - name: pvc-storage
          persistentVolumeClaim: 
            claimName: pvc-volume
      restartPolicy: Always
