---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafanadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanadep
  template:
    metadata:
      labels:
        app: grafanadep
    spec:
      containers:
      - image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
          - containerPort: 3000
      restartPolicy: Always
