---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafanadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanadep
  template:
    metadata:
      labels:
        app: grafanadep
    spec:
      containers:
      - image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: pvc-storage
      volumes:
        - name: pvc-storage
          persistentVolumeClaim: 
            claimName: pvc-volume
      restartPolicy: Always
