apiVersion: v1
kind: Service
metadata:
  name: grafanadep
spec:
  ports:
  - port: 80 #port to export outwards
    protocol: TCP
    targetPort: 3000 #port to target on pod
  type: LoadBalancer
  loadBalancerIP: 192.168.0.11
  selector:
    app: grafanadep