---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esdep
  template:
    metadata:
      labels:
        app: esdep
    spec:
      containers:
      - image: elasticsearch:7.10.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
          - containerPort: 9200
          - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        resources:
          requests:
            memory: "650Mi"
            cpu: "100m"
          limits:
            memory: "650Mi"
            cpu: "1000m"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch/config/elasticsearch.yml
            name: pvc-storage
          - mountPath: /usr/share/elasticsearch/data
            subPath: elasticsearch/data
            name: pvc-storage
      volumes:
        - name: pvc-storage
          persistentVolumeClaim: 
            claimName: pvc-volume
      restartPolicy: Always
