apiVersion: v1
kind: Service
metadata:
  name: esdep
spec:
  ports:
  - port: 9200 # external port
    protocol: TCP
    targetPort: 9200 # port in container
  type: LoadBalancer
  selector:
    app: esdep
  #type: NodePort
