---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:5.6.0-apache
        imagePullPolicy: IfNotPresent
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: dbuser
        - name: WORDPRESS_DB_PASSWORD
          value: dbpass
        - name: WORDPRESS_DB_NAME
          value: db
        # ports:
        #   - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "5m"
          limits:
            memory: "150Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /var/www/html
            name: pvc-storage
            subPath: wordpress
      volumes:
        - name: pvc-storage
          persistentVolumeClaim: 
            claimName: pvc-volume
      restartPolicy: Always
      terminationGracePeriodSeconds: 2