apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - port: 80 #port to export outwards
    protocol: TCP
    targetPort: 80 #port to target on pod
  type: LoadBalancer
  loadBalancerIP: 192.168.0.17
  selector:
    app: wordpress