---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          value: dbpass
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
        - name: MYSQL_ROOT_HOST
          value: '%'
        ports:
          - containerPort: 3306
        resources:
          requests:
            memory: "220Mi"
            cpu: "5m"
          limits:
            memory: "300Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: pvc-storage
            subPath: mysql
      volumes:
        - name: pvc-storage
          persistentVolumeClaim: 
            claimName: pvc-volume
      restartPolicy: Always
      terminationGracePeriodSeconds: 2